Upstream refresh (from hans-vervaart/ssh-batch)

diff --git a/ssh-batch b/ssh-batch
--- a/ssh-batch
+++ b/ssh-batch
@@ -24,6 +24,13 @@
 #      export <InLineFileName>_var=value
 #    will be available as $var in the inline
 #
+# The --bg-session-throttle <value> will wait if the amount of parallel
+# sessions exceeds the <value>, it will continue when the number of
+# sessions is droped 10% of the <value>
+#
+# -> The hidden option ---bg-session-throttle-hysteresis <value>, controls
+#    the number of sessions to drop for continueation.
+#
 # An insource file can be setup to control the defaults. A search will be done
 # in $HOME, the dir where the script resides and /etc. When a file is found,
 # only that will be insourced and the search will be stopped.
@@ -34,14 +41,14 @@
 # required controls, without the .ssh-batch to be in the way.
 #
 # The hidden option + arg ---info-sep <seperators>
-#   export ___info_sep_ARG=':_'
+#   export ___info_sep_ARG=',_'
 # Enables the facility to add info about the hostname to the hostname. Handy to
-# add environment information. (for example lin1234:DEV). The first char will
+# add environment information. (for example lin1234,DEV). The first char will
 # also be used to check for a second field, where the ip address can be placed
-# when a system is not in DNS (for example lin1234:DEV_PHP:192.168.1.2). 
+# when a system is not in DNS (for example lin1234,DEV_PHP,192.168.1.2). 
 # Background log files will come back as lin1234_DEV_PHP
 # The next char(s) in the ___info_sep_ARG will be used for alternative
-# info seperator using ':_' will lin1234_DEV_PHP works like lin1234:DEV_PHP
+# info seperator using ',_' will lin1234_DEV_PHP works like lin1234,DEV_PHP
 #
 # When a hostname includes a '/' character, the script assumes that a filename
 # is passed instead of a hostname.  Files with hostnames can hold comment
@@ -53,6 +60,8 @@
 # the name to distinct a filename from a hostname (like on the command line).
 # Only hostnames can be 'soft' commented.
 #
+# When a hostname includes a '^' character, the script assumes that the
+# hostname includes a jump-host (jumphost^targethost).
 #
 # The hidden option + arg ---check-hostname <script>, or setting
 #   export ___check_hostname="<script>"
@@ -88,6 +97,26 @@
 # Requires: _option_processor
 # Requires: ssh_askpass
 #
+########################### extra help ########################################
+#Usage:# The hosts argument can be a single host name or multiple hostnames.
+#Usage:#
+#Usage:# Multiple hostnames are multiple arguments. Arguments with a / are 
+#Usage:# text files containing hostnames. Hostname files can be nested.
+#Usage:# A hostname can contain a port (hostname:port), which will be passed as:
+#Usage:#
+#Usage:#   #ssh -p port hostname 
+#--all-hosts#           Enables the hostnames with a 'soft' comment (- or %).
+#--bg-disable#          Disable background runs, when --bg-log-dir is provided.
+#--bg-log-dir#          Background logs directory and enable background runs.
+#--bg-session-throttle# Maximum background runs.
+#--bg-timeout#          The wait for all background runs time-out.
+#--exit-status#         Add the EXIT_STATUS of the inline to the output.
+#--hostnames#           Add the hostname to the output.
+#--no-info#             No info messages, only ssh command and host output.
+#--no-ssh-askpass#      Disable ssh_askpass usage (when ssh-keys are used).
+#--quiet#               Only host output.
+#--ssh-option#          Options to be bassed to the ssh command.
+#--tags#                Add tags (inline names surrounded by { } in the output.
 ###############################################################################
 
 #
@@ -96,14 +125,15 @@
 #
 # By adding this variable, extra information about the host can be added
 # and will be added to the output logfile
-#___info_sep_ARG=':_'
+#___info_sep_ARG=',_'
 
 # The script which can be used to check the hostname for 'correction' like
 # adding a domain name.
 #___check_hostname_ARG=check_hostname
 
 # Defaults for options
-__bg_timout_ARG="10"
+__bg_timeout_ARG="10"
+__bg_session_throttle_ARG="0"
 __ssh_option_ARG=("NumberOfPasswordPrompts=1" "StrictHostKeyChecking=no")
 _help_show_args="hosts [[- adhoc-cmds]|[-- inline-files]][--- args]"
 
@@ -122,18 +152,24 @@ then
    export PATH
 fi
 
-# Check is everything is on it's place
-for Tool in _option_processor ssh_askpass
-do
-   if ! which $Tool 2>&1 | grep '^/' > /dev/null 2>&1
-   then
-      echo "! [ERROR] $Tool not found, unable to run"
-      exit 1
-   fi
-done
+# Check if _option_processor and ssh_askpass can be found
+if [ ! -r $RunDir/_option_processor ]
+then
+   echo "! [ERROR] $RunDir/_option_processor not found, unable to run"
+   exit 1
+elif ! which ssh_askpass 2>&1 | grep '^/' > /dev/null 2>&1
+then
+   echo "! [ERROR] ssh_askpass not found, unable to run"
+   exit 1
+fi
 
-# Run the _option_processor from the PATH
-$(which _option_processor 2>&1 | grep -v ' no ' | sed 's,^/,. /,')
+# Run the _option_processor from the $RunDir
+. $RunDir/_option_processor
+
+if [ "$__quiet" = "yes" ]
+then
+   __no_info="yes"
+fi
 
 InLine2Command()
 {
@@ -195,13 +231,13 @@ InLine2Command()
          grep -v '^$' | tr '\n' ';' | \
          sed -e 's/;*;/;/g' \
              -e 's/;2;/;;/g' ${Sed_SshInNextScript[@]} \
-             -e 's,\\ *;,,g' \
-             -e 's,\([(]\) *;,\1,g' \
-             -e 's,( *) *; *{ *;,(){,g' \
-             -e 's,\(do\) *;,\1,g' \
-             -e 's,\(then\) *;,\1,g' \
-             -e 's,\(else\) *;,\1,g' \
-             -e 's,\(in\) *;,\1,g' \
+             -e 's,\\[[:space:]]*;,,g' \
+             -e 's,\([(]\)[[:space:]]*;,\1,g' \
+             -e 's,([[:space:]]*)[[:space:]]*;[[:space:]]*{[[:space:]]*;,(){,g'\
+             -e 's,\([;[:space:]]do\)[[:space:]]*;,\1,g' \
+             -e 's,\([;[:space:]]then\)[[:space:]]*;,\1,g' \
+             -e 's,\([;[:space:]]else\)[[:space:]]*;,\1,g' \
+             -e 's,\([[:space:]]in\)[[:space:]]*;,\1,g' \
              -e "s/^[[:space:]]*/$ExitStatusOpen(/" \
              -e "s,;*\$,)2>\&1${ExitStatusClose}${SedTag};,"
       fi
@@ -253,9 +289,47 @@ CheckHostName()
    if [ "$___check_hostname_ARG" != "" ] &&
       which $___check_hostname_ARG 2> /dev/null | grep '^/' > /dev/null 2>&1
    then
-      $___check_hostname_ARG "$1" "$2" "$3" "$4" 2> /dev/null
+      $___check_hostname_ARG "$1" "$2" "$3" "$4"
    else
       echo $1
+   fi
+}
+
+WaitForBackGroundSessions() # $1=Message $2=NrOfPsToContinue $3=NrOfPsToWait 
+{
+   TotalPs=$(echo "$PIDs" | wc -w)
+   ActivPs=$(ps u $PIDs | grep -v '^USER' | wc -l)
+   if [ $TotalPs -gt 0 ] && [ $ActivPs -ge $3 ] && [ $3 -gt 0 ]
+   then
+      echo "$1"
+      if echo $__bg_timeout_ARG | grep -q '^[1-9][0-9]*$'
+      then
+         Wait=$(($__bg_timeout_ARG*60))
+      else
+         Wait=213
+      fi
+      Step=1
+      ActivPs=$(($2+1))
+      Len=$(printf "%s" "$TotalPs" | wc -m)
+      while [ $Wait -gt 0 ] && [ $ActivPs -gt $2 ]
+      do
+         ActivPs=$(ps u $PIDs | grep -v '^USER' | wc -l)
+         printf "Waiting for %0*i/%0*i sessions to finish (%02i:%02i)\r" \
+                "$Len" "$ActivPs" "$Len" "$TotalPs" \
+                "$(expr $Wait / 60)" "$(expr $Wait % 60)"
+         Wait=$(expr $Wait - $Step)
+         if [ $ActivPs -gt $2 ]
+         then
+            sleep $Step
+         fi
+      done
+      echo
+      ActivePids="$(ps u $PIDs | grep -v '^USER' | awk '{print $2}' | \
+                   tr '\n' ' ' | sed -e 's/^ //' -e 's/ $//')"
+      if [ "$ActivePids" != "" ] && [ $(echo "$ActivePids" | wc -w) -gt $3 ]
+      then
+         echo "# [CHECK] Still active PIDs: $ActivePids"
+      fi
    fi
 }
 
@@ -437,10 +511,29 @@ then
    fi
 fi
 
+# Setup the backround wait levels for the number of processes
+MaxPs=$(echo $__bg_session_throttle_ARG | egrep '^[0-9]{1,}$')
+if [ "$MaxPs" = "" ] || [ $MaxPs -lt 2 ]
+then
+   MaxPs=0
+   MinPs=0
+else
+   MinPs=$(($MaxPs-$(echo $___bg_session_throttle_hysteresis_ARG | \
+                     sed 's/^$/0/' | egrep '^[0-9]{1,}$')))
+   if [ $MinPs -lt 1 ] || [ $MinPs -ge $MaxPs ]
+   then
+      MinPs=$(($MaxPs-($MaxPs/10)))
+      if [ $MinPs -lt 1 ] || [ $MinPs -eq $MaxPs ]
+      then
+         MinPs=1
+      fi
+   fi
+fi
+
 for Hostname in $HostNames
 do
    # Remove additional information in the hostname
-   UserName=$(echo $Hostname | grep '@' | sed -e 's/@.*//')
+   UserName=$(echo $Hostname | grep '@' | sed -e 's/@[^@]*$//')
    Hostname=$(echo $Hostname | sed 's/.*@//')
    if [ "$___info_sep_ARG" = "" ]
    then
@@ -457,6 +550,33 @@ do
       HostIpAd=$(echo $Hostname|awk -F ${___info_sep_ARG:0:1} '{print $3'})
    fi
 
+   unset HostOpts
+   # Check for Jumphost info (^). Multiple jumphosts will be comma separated
+   if echo $HostName | grep -q '\^'
+   then
+      # Multiple jumphosts are converted to a , seperated list
+      HostOpts=($(echo $HostName | sed 's/\^[^^]*$//' | \
+                  tr '^' ',' | sed 's/^./-J \0/'))
+      if [ "$__no_info" != "yes" ]
+      then
+         echo "${HostOpts[@]}" | sed -e 's/^/# [INFO] Jump-host:/' \
+                                    -e 's/-J//g' >&2
+      fi
+
+      # Correct the HostName
+      HostName=$(echo $HostName | awk -F^ '{print $NF}')
+   fi
+
+   # Check for :port
+   if echo $HostName | grep -q ':'
+   then
+      HostOpts[${#HostOpts[@]}]='-p'
+      HostOpts[${#HostOpts[@]}]=$(echo $HostName | awk -F: '{print $2}')
+
+      # Correct the HostName
+      HostName=$(echo $HostName | awk -F: '{print $1}')
+   fi
+
    # Run the hostname correction plugin
    Host=$(CheckHostName "$HostName" "$UserName" "$HostInfo" "$HostIpAd")
 
@@ -465,13 +585,38 @@ do
 
    if [ "$Host" = "" ]
    then
-      echo "# Hostname ($Hostname) check failed, skipping host" >&2
-   else
-      if [ "$HostInfo" = "" ]
+      if [ "$__bg_log_dir" = "yes" ]
       then
-         echo "# ssh" ${SshOpts[@]} ${UserName}${Host} >&2
+         OutputFile="$(echo $__bg_log_dir_ARG | sed 's,/*$,,')/${HostName}"
+         if [ "$HostInfo" != "" ]
+         then
+            OutputFile="${OutputFile}_${HostInfo}"
+         fi
       else
-         echo "# ssh" ${SshOpts[@]} ${UserName}${Host} "($HostInfo)" >&2
+         OutputFile=/dev/null
+      fi
+      if [ "$__quiet" = "yes" ]
+      then
+         # Log the failure
+         echo "# Hostname ($Hostname) check failed, skipping host" \
+              > $OutputFile
+      else
+         echo "# Hostname ($Hostname) check failed, skipping host" \
+              | tee $OutputFile >&2
+      fi
+   else
+      WaitForBackGroundSessions \
+         "Session throttle $MaxPs reached, continueing at $MinPs" $MinPs $MaxPs
+      # Quiet mode?
+      if [ "$__quiet" != "yes" ]
+      then
+         if [ "$HostInfo" = "" ]
+         then
+            echo "# ssh" ${SshOpts[@]} ${HostOpts[@]} ${UserName}${Host} >&2
+         else
+            echo "# ssh" ${SshOpts[@]} ${HostOpts[@]} ${UserName}${Host} \
+                 "($HostInfo)" >&2
+         fi
       fi
       if [ "$__bg_log_dir" = "yes" ]
       then
@@ -480,53 +625,32 @@ do
          then
             OutputFile="${OutputFile}_${HostInfo}"
          fi
-         echo "# Output send to ${OutputFile}" >&2
+         if [ "$__quiet" != "yes" ]
+         then
+            echo "# Output send to ${OutputFile}" >&2
+         fi
          if [ "$__bg_disable" = "yes" ] || [ "$SETSID" = "" ]
          then
-            $SETSID ssh ${SshOpts[@]} ${UserName}${Host} "${Command}" \
-                        > ${OutputFile} 2>&1
+            $SETSID ssh ${SshOpts[@]} ${HostOpts[@]} ${UserName}${Host} \ 
+                        "${Command}" > ${OutputFile} 2>&1
          else
-            $SETSID ssh ${SshOpts[@]} ${UserName}${Host} "${Command}" \
-                        > ${OutputFile} 2>&1 &
+            $SETSID ssh ${SshOpts[@]} ${HostOpts[@]} ${UserName}${Host} \
+                        "${Command}" > ${OutputFile} 2>&1 &
             PIDs="$PIDs $!"
          fi
       else
-         $SETSID ssh ${SshOpts[@]} ${UserName}${Host} "${Command}"
+         if [ "$__hostnames" = "yes" ]
+         then
+            $SETSID ssh ${SshOpts[@]} ${HostOpts[@]} ${UserName}${Host} \
+                        "${Command}" | sed "s/^/${HostName}:/"
+         else
+            $SETSID ssh ${SshOpts[@]} ${HostOpts[@]} ${UserName}${Host} \
+                        "${Command}"
+         fi
       fi
    fi
 done
 
-if echo "$PIDs" | grep '[0-9]' 2>&1 > /dev/null
-then
-   echo "Background sessions running"
-   if echo $__bg_timout_ARG | grep -q '^[1-9][0-9]*$'
-   then
-      Wait=$(($__bg_timout_ARG*60))
-   else
-      Wait=213
-   fi
-   Step=1
-   ActivPs=1
-   TotalPs=$(echo "$PIDs" | wc -w)
-   Len=$(printf "%s" "$TotalPs" | wc -m)
-   while [ $Wait -gt 0 ] && [ $ActivPs -gt 0 ]
-   do
-      ActivPs=$(ps u $PIDs | grep -v '^USER' | wc -l)
-      printf "Waiting for %0*i/%0*i sessions to finish (%02i:%02i)\r" \
-             "$Len" "$ActivPs" "$Len" "$TotalPs" \
-             "$(expr $Wait / 60)" "$(expr $Wait % 60)"
-      Wait=$(expr $Wait - $Step)
-      if [ $ActivPs -gt 0 ]
-      then
-         sleep $Step
-      fi
-   done
-   echo
-   ActivePids="$(ps u $PIDs | grep -v '^USER' | awk '{print $2}' | \
-                tr '\n' ' ' | sed -e 's/^ //' -e 's/ $//')"
-   if [ "$ActivePids" != "" ]
-   then
-      echo "# [CHECK] Still active PIDs: $ActivePids"
-   fi
-fi
+# Final wait
+WaitForBackGroundSessions "Background sessions running" 0 1
 
