fixing typos

diff --git a/ssh_askpass b/ssh_askpass
--- a/ssh_askpass
+++ b/ssh_askpass
@@ -26,7 +26,7 @@
 #  $(ssh_askpass --exports hans have verha)
 #
 #
-# -> disadvantige: You have to enter 3 passwords when running the script.
+# -> disadvantage: You have to enter 3 passwords when running the script.
 #                  By setting up the vault, only the vault secret will
 #                  be requested.
 #
@@ -363,10 +363,10 @@ then
             export Passw PwdCh
             if [ ${#PwdCh} -eq 0 ] || \
                ! (echo "$RANDOM" | \
-                  openssl enc -des -pass env:Passw \
+                  $OPEN_SSL enc -des -pass env:Passw \
                               -in /dev/stdin \
                               -out /dev/stdout -e | \
-                  openssl enc -des -pass env:PwdCh \
+                  $OPEN_SSL enc -des -pass env:PwdCh \
                               -in /dev/stdin \
                               -out /dev/stdout -d ) > /dev/null 2>&1
             then
@@ -447,7 +447,7 @@ then
                 sed 's/.*://' | $OPEN_SSL base64 -d)"
          if [ ${#Pwd} -eq 0 ]
          then
-            echo $* "<$(basename $0) FAILED (unkown account)>" >&2
+            echo $* "<$(basename $0) FAILED (unknown account)>" >&2
             exit 1
          fi
          echo $* "<$(basename $0)>" >&2
